### ISSUE TITLE
[CRITICAL] Registering New Student in Long Form causes 500 Error

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/Student-Registration-React-Web#102]
To reproduce:
https://new-student-registration.herokuapp.com/

1. Authenticate in with a new or existing number.
2. fill in required fields
3. submit
Result: 500 Error (popup)
Details Attaching...

**Comment by AleksandrMolchagin** [comment]
Error:
![image](https://github.com/user-attachments/assets/94942d54-3444-40e2-9e57-f2cabc933b61)

Possible fix (in `api.js`):
![image](https://github.com/user-attachments/assets/7b0c281b-30da-4cfb-8a5a-55fc41aa90e9)
