### ISSUE TITLE
School selection dropdown should clear when user chooses a different region

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/Student-Registration-React-Web#25]
presently, if a school has already been selected (e.g. user is updating a record), choosing a new region doesn't clear the school selection which is confusing. 
Cleaner UX will be for the school choice to be cleared anytime the user changes the value in either dropdown.
The currently set value should appear highlighted in the dropdown is there is a value

**Comment by lautirozen** [comment]
DONE
