### ISSUE TITLE
Check for Waiver Acceptance in Waiver history

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/Student-Registration-React-Web#36]
will need support from the API for this. (GET /api/contacts/${ContactId})

1. check for the active waiver for the region and date and if there is one:
2. check the waiver histry for the contact to see if it already is complete
3. if it is complete, show the box as checked, but allow the user to display it again
4. if it is not complete, require acceptance

**Comment by lautirozen** [comment]
DONE
