### ISSUE TITLE
Clicking DONE, form reloads anyway with confusing message

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/Student-Registration-React-Web#38]
after the student reg form is submitted and I pick DONE, the form reloads anyway for a moment, says "Student Records Found" and then loads scoresU.

Can we make the link to ScoresU happen before the Auth Reload occurs? Its not a deal breaker but we have to remove and and all confusion from the Student Reg UX.

**Comment by lautirozen** [comment]
DONE
