### ISSUE TITLE
Optional assignment of a student to a team season

### ISSUE THREAD

**Issue by Abbybretado** [AmericaSCORESBayArea/Student-Registration-React-Web#74]
Coach will have the option to assign a student to a team season when registering or updating a record:

### API Dependency
https://github.com/AmericaSCORESBayArea/salesforce-data-api/issues/191

**Coach Registration/Record Creation:**
Coach accesses the registration or record creation page.
Coach is presented with the option to use the Short Form.
If the Short Form is selected:
Coach enters the student's First Name.
Coach has the option to enter Last Name, Gender, and Ethnicity (all optional fields).
Coach selects the Region/School/Team for the student.
Coach has the option to assign the student to a specific Team Season during this step.

**Record Update:**
Coach accesses the record update page.
Coach sees the option to use the Short Form.
If the Short Form is selected:
Coach views the existing record details (if any) populated from previous entries.
Coach has the option to update the student's First Name, Last Name, Gender, Ethnicity, and/or Region/School/Team.
Coach can also optionally assign the student to a different Team Season during this step.

**Switch to Long Form:**
At any point, the coach can choose to switch to the Long Form.
Coach selects the option to switch to the Long Form.
The system carries forward the values from the Short Form to the Long Form.

**Optional Assignment to Team Season:**
Throughout the Short Form or Long Form entry process, the coach has the option to assign the student to a specific Team Season.
If selected, the coach chooses the appropriate Team Season from the available options.
The system records this assignment along with the student's other details.
![Image](https://github.com/AmericaSCORESBayArea/student-registration/assets/1458369/1045b899-7fa8-4bff-9a0d-cce227794192)

**Comment by CritiqalPete** [comment]
replaces https://github.com/AmericaSCORESBayArea/student-registration/issues/241

**Comment by CritiqalPete** [comment]
@lautirozen is this in Progress? It's the top priority for feature enhancement

**Comment by CritiqalPete** [comment]
@za-zohaib id working on adding this to the bottom of the Student Registration (long form)

**Comment by za-zohaib** [comment]
Yes will start on this soon. Thanks

**Comment by CritiqalPete** [comment]
Note: We may be asked to add this to the Parent Flow at some point soon too. Keep in mind.

**Comment by CritiqalPete** [comment]
@za-zohaib This is a priority for the Coach Flow. And the Team Selection needs to be removed from the Parent Flow
