### ISSUE TITLE
(Critical) Disable Registration Requirement for Parent Email

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/Student-Registration-React-Web#77]
A new approach for accessibility is planned for over the Summer done by Aug 1, so anything we do now would presumably be for now through the end of the first week of June and then be reconsidered over the Summer.

### Program Requirement:
The Spring 2024 push for registrations needs to limit barriers to recording the minimum amount of registration data.

### Change Request:
Set _Parent Email_ to NOT REQUIRED for all Registration flows (Coach and Parent/Guardian)

###Dependency:
Data API should accept a POST or PATCH request with no data/null in this field.

**Comment by CritiqalPete** [comment]
@AleksandrMolchagin can you please verify the API does not require this field and @andrerhodes likewise on Salesforce?

**Comment by andrerhodes** [comment]
<img width="1016" alt="Screenshot 2024-05-23 at 7 29 39 PM" src="https://github.com/AmericaSCORESBayArea/Student-Registration-React-Web/assets/113068792/ac3179d5-e514-4e3d-b317-c58027fd282e">


This is the Salesforce side look at Parent Email address field on the Contact object. It is attached to a few reports  and the student layout but it is not required on this end.

**Comment by AleksandrMolchagin** [comment]
No dependencies on the API side. Here is an example of creation & updating contact:

**CREATE (POST)**
<img width="1038" alt="image" src="https://github.com/AmericaSCORESBayArea/Student-Registration-React-Web/assets/47938394/ec0fba26-eff9-416d-9cb8-42351b2f4b49">

**UPDATE (PATCH)**
<img width="1038" alt="image" src="https://github.com/AmericaSCORESBayArea/Student-Registration-React-Web/assets/47938394/c25ba198-dc90-4715-b1e1-8f93ac5e0001">

**GET** 
<img width="1038" alt="image" src="https://github.com/AmericaSCORESBayArea/Student-Registration-React-Web/assets/47938394/d92511f8-8408-4c92-b0f3-a9367323aac1">
